# Title of the site.
# Shows up in navbar and embeds
title: Memerator

# Nav Bar elements.
nav:
- title: <i class="fas fa-home"></i> Home
  url: /

# Path of URL. Used for links and stuff
url: my-website.memerator.me/nice
